version: 2.1
orbs:
    node: circleci/node@4.2.1
jobs:
    build-and-test:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                  cache-path: ~/project/node_modules
                  override-ci-command: npm install --also-dev --dry-run
            - run: npm run test
workflows:
    run-build:
        jobs:
            - build-and-test
