version: 2.1
orbs:
    node: circleci/node@4.5.0
jobs:
    test:
        executor:
            name: node/default
            tag: 14.15.4
        steps:
            - checkout
            - node/install-packages:
                  override-ci-command: npm ci --ignore-scripts
            - run:
                  command: npm run test

workflows:
    test_my_app:
        jobs:
            - test
